### ISSUE TITLE
encode-decode fails to build with 4GB ram

### ISSUE THREAD

**Issue by andres-erbsen** [samuelgruetter/riscv-coq#2]
Here is how to do 101 out of 108 cases faster than a single case in the old script: https://gist.github.com/andres-erbsen/36c06a8b0d638d27ba86214c9e973c84

The remaining 7 cases are reduced to systems of equations involving extension and bitslicing e.g. https://gist.github.com/andres-erbsen/36c06a8b0d638d27ba86214c9e973c84#file-faster-encode-decode-v-L314. Since I never managed to build the original proof, I don't know how to fix these, but this should be a way to go.

**Comment by samuelgruetter** [comment]
Thanks, that sounds promising, I'll start using that code!
Two questions:
*    I'm not so thrilled by `Ltac cbn_encode`, do you have an idea how to avoid such huge enumerations?
*    How long do you think will the final Qed take? Did you try that out?

**Comment by andres-erbsen** [comment]
- I think the pattern here is that we want to unfold encode and decode functions but not word and Z functions, but afaik is no nice way to implement that (even https://github.com/coq/coq/issues/5271 is still open, or you could try to encode that using `Arguments`, but I've had only pain with that). It might be possible to make a shorter `cbn -[bitslice signExtend ...]` or even `cbn` call do the trick, but I don't see a good argument fow why that would be the case.
- I haven't tried it, but it should relatively straightforward to make it take not longer than the proof itself.

**Comment by samuelgruetter** [comment]
Good news: The 7 remaining cases are all handled by my new `somega` tactic (a better omega which understands bitSlice and signExtend).

The whole DecodeEndode.v can now (as of 2b3890f) be compiled within 2min and 1.1GB on my machine.

Thank you so much @andres-erbsen!

**Comment by andres-erbsen** [comment]
Now that the proof is complete, you can switch from `all:` to `par: abstract (...)` to hopefully further speed up things :). Or `all:abstract(...)` to hopefully reduce memory usage.
